package me.bill.fakePlayerPlugin.api;

import java.time.Duration;
import java.util.Set;
import java.util.UUID;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public interface FppBot {
  @NotNull String getName();
  @NotNull UUID getUuid();
  @NotNull String getDisplayName();
  void setDisplayName(@NotNull String name);
  @Nullable String getSkinName();
  @NotNull Location getLocation();
  @NotNull String getWorldName();
  @Nullable Player getEntity();
  boolean isBodyless();
  boolean isFrozen();
  void setFrozen(boolean frozen);
  boolean isAlive();
  boolean isRespawning();
  boolean isChatEnabled();
  void setChatEnabled(boolean enabled);
  @Nullable String getChatTier();
  void setChatTier(@Nullable String tier);
  @Nullable String getAiPersonality();
  void setAiPersonality(@Nullable String personality);
  boolean isHeadAiEnabled();
  void setHeadAiEnabled(boolean enabled);
  boolean isSwimAiEnabled();
  void setSwimAiEnabled(boolean enabled);
  boolean isPickUpItemsEnabled();
  void setPickUpItemsEnabled(boolean enabled);
  boolean isPickUpXpEnabled();
  void setPickUpXpEnabled(boolean enabled);
  boolean isNavParkour();
  void setNavParkour(boolean enabled);
  boolean isNavBreakBlocks();
  void setNavBreakBlocks(boolean enabled);
  boolean isNavPlaceBlocks();
  void setNavPlaceBlocks(boolean enabled);
  boolean isNavSprintJump();
  void setNavSprintJump(boolean enabled);
  int getChunkLoadRadius();
  void setChunkLoadRadius(int radius);
  boolean isPveEnabled();
  void setPveEnabled(boolean enabled);
  double getPveRange();
  void setPveRange(double range);
  @Nullable String getPvePriority();
  void setPvePriority(@Nullable String priority);
  @NotNull String getSpawnedBy();
  @NotNull UUID getSpawnedByUuid();
  boolean isOwnedBy(@NotNull UUID playerUuid);
  boolean hasControllerAccess(@NotNull UUID playerUuid);
  @NotNull Set<UUID> getSharedControllerUuids();
  boolean grantControllerAccess(@NotNull UUID playerUuid);
  boolean revokeControllerAccess(@NotNull UUID playerUuid);
  @NotNull Duration getUptime();
  int getDeathCount();
  double getTotalDamageTaken();
  boolean isInWater();
  boolean isInLava();
  boolean isSprinting();
  int getPing();
}
